# Generated by Django 3.2.13 on 2022-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplisting',
            name='buyers',
            field=models.CharField(max_length=5000),
        ),
    ]
