# Generated by Django 3.2.13 on 2022-05-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0003_auto_20220517_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplisting',
            name='available_units',
        ),
    ]
