version: "3.3"
   
services:
  db:
    container_name: Pixelspace_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    networks:
#      - vuln    
  
  web:
    container_name: Pixelspace
    build: 
      context: .
    #command: sh -c "gunicorn -c gunicorn.conf.py pixelspace.asgi

    volumes:
      - .:/code
    ports:
      - "8010:8010"
    env_file:
      - ./.env.dev
    depends_on:
      - db
#    networks:
#      - vuln

#networks:
#  vuln:
#    external: True

volumes:
  postgres_data: