version: '3.3'

services:
  web:
    restart: unless-stopped
    container_name: Pixelspace
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn pixelspace.wsgi:application --bind 0.0.0.0:8088
    volumes:
      - media_volume:/mediafiles
      - static_volume:/staticfiles
    expose:
      - 8088
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: unless-stopped
    container_name: Pixelspace_db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    restart: unless-stopped
    container_name: Pixelspace_rev_proxy
    build: ./nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    ports:
      - 8010:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: