version: "3.9"
   
services:
  db:
    container_name: Pixelspace_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - vuln    
  
  web:
    container_name: Pixelspace
    build: 
      context: .
    #command: sh -c "gunicorn -c gunicorn.conf.py pixelspace.asgi

    volumes:
      - .:/code
    ports:
      - "8010:8010"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PRODUCTION=False
    depends_on:
      - db
    networks:
      - vuln

networks:
  vuln: