version: "3"

services:
  pixelspace-checker:
    container_name: pixelspace-checker
    build: .
    command: bash -c 'uvicorn example:checker.app'
    ports:
      - 8000:8000
    environment:
    - MONGO_ENABLED=1
    - MONGO_HOST=pixelspace-checker-db
    - MONGO_PORT=27017
    - MONGO_USER=root 
    - MONGO_PASSWORD=root
    logging:
      driver: none


  pixelspace-checker-db:
    image: mongo
    volumes:
      - pixelspace-checker-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: none


volumes:
  pixelspace-checker-db:
 
  
