name: enochecker_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: self-hosted
    env:
      ENOCHECKER_TEST_SERVICE_ADDRESS: 172.17.0.1
      ENOCHECKER_TEST_CHECKER_ADDRESS: 172.17.0.1
      ENOCHECKER_TEST_CHECKER_PORT: 8000

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install enochecker_test
      run: |
        python -m pip install --upgrade pip
        pip install enochecker-test
    - name: start service
      run: |
        cd service
        docker-compose up -d --build
    - name: start checker
      run: |
        cd checker
        docker-compose up -d --build
    - name: run enochecker_test
      run: |
        enochecker_test