# Generated by Django 3.2.13 on 2022-06-02 05:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pixels.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=models.SET('Unknown User'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=models.SET('Unknown User'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cert_licencse', pixels.validators.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/')),
                ('data', pixels.validators.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyers', models.CharField(max_length=5000)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000000)])),
                ('description', models.CharField(max_length=300)),
                ('sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pixels.shopitem')),
                ('reception', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Unknown User'), to='pixels.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.CharField(max_length=50)),
                ('last_post', models.CharField(max_length=50)),
                ('num_Posts', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=models.SET('Unknown User'), to=settings.AUTH_USER_MODEL)),
                ('posts', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Unknown User'), to='pixels.forumpost')),
            ],
        ),
    ]
