# Generated by Django 3.2.13 on 2022-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0002_alter_shoplisting_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cryptographic_key',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.CharField(default='You can enter your notes here...', max_length=50000),
        ),
    ]
