# Generated by Django 3.2.13 on 2022-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0003_auto_20220602_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cryptographic_key',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
