# Generated by Django 3.2.13 on 2022-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0004_alter_profile_cryptographic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='data_name',
            field=models.CharField(default='item_name.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
